### PR TITLE
Replace M2Crypt with pycrypto

### PR DESCRIPTION
**Pull request by AdamIsrael**
While writing an [AppIndicator](https://unity.ubuntu.com/projects/appindicators/) for managing my 1password keychain, I discovered 1pass. I realized I could use its existing code to manage the decryption of the keychain. I discovered, though, that M2Crypt does not work with Python 3+. I did some research on alternative libraries, and chose pycrypto. This pull request is the result of that work.

### CODE REVIEW

**Comment by georgebrock** [comment]
The code looks good to me, but the new library seems significantly slower than the current one:

```
$ git checkout master
$ python setup.py test
…
Ran 29 tests in 1.739s

OK
$ git checkout AdamIsrael-pycrypto
$ python setup.py test
Ran 29 tests in 29.919s

OK
…
```

IIRC, newer 1password vault files use higher iterations than the older files used by the test suite, which means any performance problems could be magnified in real use with a newer vault.

**Comment by AdamIsrael** [comment]
I'll do some benchmarking to see what's adding that overhead, and see if I can eliminate/reduce it.

**Comment by AdamIsrael** [comment]
Performance issue is fixed, but there are some python3 compatibility issues that still need to be addressed.

**Comment by AdamIsrael** [comment]
This latest push adds python3 compatilibity, and is ready for re-review.

**Comment by AdamIsrael** [comment]
Hey @georgebrock, will you be able to look at this soon?

**Comment by AdamIsrael** [comment]
Sorry, I just saw the invite to collaborate!

Since the tests now pass, and performance is no longer an issue, I'm going to merge this PR.

**Comment by glyph** [comment]
It's nice to see that this was updated!

Unfortunately… PyCrypto is a dead project, and is not generally recommended for use in new code.

Compare, for example, https://github.com/dlitz/pycrypto/graphs/contributors?from=2015-06-15&to=2017-07-15&type=c vs. https://github.com/pyca/cryptography/graphs/contributors?from=2015-06-15&to=2017-07-15&type=c.

Many projects needing cryptography in Python, including (just off the top of my head) Twisted Conch and Paramiko, are migrating from PyCrypto to Cryptography.

Sadly I do not have any bandwith to put forward to re-re-doing this work myself, but it would be good if someone ported this project from PyCrypto to Cryptography as well.

**Comment by AdamIsrael** [comment]
Thanks for the news. I'd been wondering about the state of cryptography in Python lately, looking at it for another project. I'll take a closer look at Cryptography and see what it'll take to port the crypto code to that.

**Comment by glyph** [comment]
Cryptography is absolutely the thing you should be using for new stuff :). Glad I caught you before your other project took off!

**Pull request merged**
